<?php if($this->getConfig('enabled')){ // start enable module?>
	<?php $this->getProducts() ?>
	<?php $_productCollection=$this->getProductCollection() ?>
	<?php
		$auto = $this->getConfig('auto');
		$itemsDefault = $this->getConfig('itemsDefault');
		$itemsDesktop = $this->getConfig('itemsDesktop');
		$itemsDesktopSmall = $this->getConfig('itemsDesktopSmall');
		$itemsTablet = $this->getConfig('itemsTablet');
		$itemsMobile = $this->getConfig('itemsMobile');
		$speed = $this->getConfig('speed');
		$next_back = $this->getConfig('next_back');
		$nav_ctrl = $this->getConfig('nav_ctrl');
	?>
	<div class="ma-newproductslider-container">
		<?php				
			if ( !$this->getConfig('width_thumbnail') ){
				$w_thumbnail = 135;
			} else {
				$w_thumbnail = $this->getConfig('width_thumbnail');
			}
			if( !$this->getConfig('height_thumbnail') ){
				$h_thumbnail = 135;
			 }
			else {
				$h_thumbnail = $this->getConfig('height_thumbnail');
			}
		?>
		<?php if($this->getConfig('title')){?>
			<div class="ma-newproductslider-title ma-title"><h2><?php echo $this->getConfig('title')?></h2></div>
		<?php }?>
		<?php if(!$_productCollection->count()): ?> 
			<div class="ma-newproductslider">	
				<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
			<?php
			$rows = $this->getConfig('row_show');
			?>
				<div class="new-content">
				<ul class="owl">
					<?php $_collectionSize = $_productCollection->count() ?>
					<?php $i=0; foreach ($_productCollection as $_product): ?>
					<?php if($i %$rows == 0) echo "<li class='newproductslider-item'>"; ?>
						<div class="item-inner">
							<div class="ma-box-content">
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w_thumbnail, $h_thumbnail); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" /></a>
								<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h2>
								
								<?php if( $this->getConfig('show_price') ): ?>
									<div class="price-box">
										<?php
										$sym = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); 
										$price = $_product->getPrice();
										$specialprice = $_product->getFinalPrice();
										if($price != $specialprice){
										if($price != ''){
										echo '<p class="old-price"><span class="price-label">';
										echo $this->__('Regular Price'). ': </span>';
										echo '<span class="price">'.$sym.''.number_format($price,2).'</span></p>';
										}
										if($specialprice != '')
										{
										echo '<p class="special-price">
										<span class="price-label">Special Price</span>
										<span class="price">'.$sym.''.number_format($specialprice,2).'</span>
										</p> ';
										} 
										}else {
										echo '<div class="price-boxs">
										<span class="regular-price">
										<span class="price">'.$sym.''.number_format($price,2).'</span>                                    
										</span>    
										</div>';    
										}
										?>
									</div>
								<?php endif; ?>
								<?php if($this->getConfig('review')): ?>
									<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
								<?php endif; ?>
								<div class="actions">
									<?php if ($this->getConfig('addtocart')) { ?>
										<?php if($_product->isSaleable()): ?>
											<button type="button"  class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
										<?php else: ?>
											<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
										<?php endif; ?>
									<?php }?>
									<?php if( $this->getConfig('addtowishlist') || $this->getConfig('addtocompare') ){?>
										<ul class="add-to-links">
											<?php if( $this->getConfig('addtowishlist')): ?>
												<?php if ($this->helper('wishlist')->isAllow()) : ?>
													<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"  class="link-wishlist fa fa-heart"><em><?php echo $this->__('Add to Wishlist') ?></em></a></li>
												<?php endif; ?>
											<?php endif; ?>
											<?php if( $this->getConfig('addtocompare')): ?>
												<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
													<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare fa fa-refresh"><em><?php echo $this->__('Add to Compare') ?></em></a></li>
												<?php endif; ?>
											<?php endif; ?>
										</ul>
									<?php }?>
								</div>
								<?php if( $this->getConfig('description')){?>
									<div class="ma-desc">
										<?php if(!$this->getConfig('maxlength')){?>
											<?php echo nl2br($this->htmlEscape($_product->getShortDescription())) ?>
										<?php } else {?>
											<?php echo nl2br($this->cut_string_newproductslider($this->htmlEscape($_product->getShortDescription()),$this->getConfig('maxlength'))) ?>			            
										<?php }?>			                    
									</div>
								<?php }?>
							</div>
						</div>
						<?php $i++;?>
						<?php if($i %$rows == 0) echo "</li>"; ?>                  
					<?php endforeach; ?>
						<?php if($i %$rows != 0) echo "</li>"; ?>
				</ul>
				</div>
                <script type="text/javascript">
					$jq(document).ready(function(){
						$jq(".ma-newproductslider-container .owl").owlCarousel({
							autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
							items : <?php if($itemsDefault) echo $itemsDefault; else echo '5'; ?>,
							itemsDesktop : [1199,<?php if($itemsDesktop) echo $itemsDesktop; else echo '5'; ?>],
							itemsDesktopSmall : [980,<?php if($itemsDesktopSmall) echo $itemsDesktopSmall; else echo '3'; ?>],
							itemsTablet: [768,<?php if($itemsTablet) echo $itemsTablet; else echo '2'; ?>],
							itemsMobile : [479,<?php if($itemsMobile) echo $itemsMobile; else echo '1'; ?>],
							slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
							paginationSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
							rewindSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
							navigation : <?php if($next_back) echo 'true'; else echo 'false'; ?>,
							stopOnHover : true,
							pagination : <?php if($nav_ctrl) echo 'true'; else echo 'false'; ?>,
						});
					});
				</script>
		<?php endif; ?> 
	</div> 
<?php } ?>


