<div class="top-banner-home">
	<div class="container">
		<div class="row">
			<div class="col-md-9 col-xs-12">
				<?php  echo $this->getLayout()->createBlock('banner7/banner7')->setTemplate('magentothem/banner7/banner7.phtml')->toHtml(); ?>
			</div>
			<div class="col-md-3 col-xs-12">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('banner_right_home3')->toHtml();?>
			</div>
		</div>
	</div>
</div>
